# Generated by Django 5.2.12 on 2026-03-25 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("master", "0002_align_integer_pks"),
    ]

    operations = [
        # Table `accounting_coa` already exists (legacy / pre-provisioned).
        # We only register the model in Django's migration state, without
        # issuing CREATE TABLE / CREATE INDEX statements.
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.CreateModel(
                    name="Coa",
                    fields=[
                        ("id", models.AutoField(primary_key=True, serialize=False)),
                        ("code", models.CharField(db_index=True, max_length=50)),
                        ("name", models.CharField(max_length=255)),
                        ("update_at", models.DateTimeField(blank=True, null=True)),
                        ("is_active", models.BooleanField(db_index=True, default=True)),
                        (
                            "parent",
                            models.ForeignKey(
                                blank=True,
                                null=True,
                                on_delete=django.db.models.deletion.PROTECT,
                                related_name="children",
                                to="master.coa",
                            ),
                        ),
                    ],
                    options={
                        "db_table": "accounting_coa",
                        "ordering": ["code", "id"],
                        "managed": False,
                    },
                ),
                migrations.AddIndex(
                    model_name="coa",
                    index=models.Index(fields=["parent", "code"], name="idx_coa_parent_code"),
                ),
                migrations.AddIndex(
                    model_name="coa",
                    index=models.Index(fields=["is_active", "code"], name="idx_coa_active_code"),
                ),
                migrations.AddConstraint(
                    model_name="coa",
                    constraint=models.UniqueConstraint(fields=("code",), name="uniq_coa_code"),
                ),
            ],
        ),
    ]

