# Generated by Django 5.2.12 on 2026-03-25 12:45

from django.db import migrations


def _rename_created_at_to_update_at_sql(table_name: str) -> str:
    # PostgreSQL does not support IF EXISTS for "RENAME COLUMN".
    # Use a DO block to keep the migration idempotent across environments.
    return f"""
DO $$
BEGIN
  IF EXISTS (
    SELECT 1
    FROM information_schema.columns
    WHERE table_schema = 'public'
      AND table_name = '{table_name}'
      AND column_name = 'created_at'
  ) AND NOT EXISTS (
    SELECT 1
    FROM information_schema.columns
    WHERE table_schema = 'public'
      AND table_name = '{table_name}'
      AND column_name = 'update_at'
  ) THEN
    EXECUTE 'ALTER TABLE {table_name} RENAME COLUMN created_at TO update_at';
  END IF;
END $$;
""".strip()


class Migration(migrations.Migration):

    dependencies = [
        ("master", "0003_create_coa"),
    ]

    operations = [
        migrations.RunSQL(
            sql=_rename_created_at_to_update_at_sql("accounting_coa"),
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            sql=_rename_created_at_to_update_at_sql("accounting_cashbook"),
            reverse_sql=migrations.RunSQL.noop,
        )
    ]

