# Generated by Django 5.2.12 on 2026-03-26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("master", "0008_unique_product_category_name"),
    ]

    operations = [
        # Table `legal_entity_type` already exists in the database.
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.CreateModel(
                    name="LegalEntityType",
                    fields=[
                        ("id", models.AutoField(primary_key=True, serialize=False)),
                        ("code", models.CharField(max_length=10, unique=True)),
                        ("name", models.CharField(max_length=100)),
                        ("is_active", models.BooleanField(default=True)),
                    ],
                    options={
                        "db_table": "legal_entity_type",
                        "managed": False,
                        "ordering": ["code", "id"],
                    },
                )
            ],
        )
    ]

