# Generated by Django 5.2.12 on 2026-03-22 12:35
#
# Deploy: run ``python manage.py migrate`` on every release.
# If these tables already existed before this migration was added, run once:
#   python manage.py migrate sales --fake-initial
# Requires existing PostgreSQL tables: product, table_number, tax (master data).

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('master', '0002_align_integer_pks'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, default='', max_length=100)),
                ('phone', models.CharField(blank=True, default='', max_length=50)),
            ],
            options={
                'db_table': 'customer',
                'constraints': [models.UniqueConstraint(fields=('name', 'phone'), name='unique_name_phone')],
            },
        ),
        migrations.CreateModel(
            name='SalesOrder',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('time_transaction', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('state', models.CharField(choices=[('draft', 'Draft'), ('confirmed', 'Confirmed'), ('void', 'Void')], db_index=True, default='draft', max_length=20)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales_orders', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_orders', to='sales.customer')),
                ('table_number', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_orders', to='master.tablenumber')),
            ],
            options={
                'db_table': 'sales_order',
                'ordering': ['-time_transaction', '-id'],
            },
        ),
        migrations.CreateModel(
            name='SalesOrderLine',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=20)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('is_active', models.BooleanField(default=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_order_lines', to='master.product')),
                ('sales_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='sales.salesorder')),
            ],
            options={
                'db_table': 'sales_order_line',
            },
        ),
        migrations.CreateModel(
            name='SalesOrderLineTax',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('sales_order_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_taxes', to='sales.salesorderline')),
                ('tax', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_order_line_taxes', to='master.tax')),
            ],
            options={
                'db_table': 'sales_order_line_tax',
            },
        ),
        migrations.AddIndex(
            model_name='salesorder',
            index=models.Index(fields=['-update_at'], name='idx_so_update_at'),
        ),
        migrations.AddIndex(
            model_name='salesorder',
            index=models.Index(fields=['state', '-update_at'], name='idx_so_state_update_at'),
        ),
        migrations.AddIndex(
            model_name='salesorder',
            index=models.Index(fields=['created_by'], name='idx_so_created_by'),
        ),
        migrations.AddIndex(
            model_name='salesorderline',
            index=models.Index(fields=['sales_order', 'id'], name='idx_sol_order_id'),
        ),
        migrations.AddConstraint(
            model_name='salesorderlinetax',
            constraint=models.UniqueConstraint(fields=('sales_order_line', 'tax'), name='sales_order_line_tax_sales_order_line_id_tax_id_key'),
        ),
    ]
