# Generated by Django 5.2.12 on 2026-03-22 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_code_counter_and_sales_order_code"),
        ("sales", "0001_initial"),
    ]

    operations = [
        # Idempotent for DBs that already added ``code`` manually (varchar length may differ).
        migrations.RunSQL(
            sql="""
            ALTER TABLE sales_order ADD COLUMN IF NOT EXISTS code VARCHAR(100) NULL;
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            sql="""
            DO $$
            BEGIN
                IF NOT EXISTS (
                    SELECT 1 FROM pg_constraint c
                    JOIN pg_class t ON c.conrelid = t.oid
                    WHERE t.relname = 'sales_order' AND c.conname = 'sales_order_code_unique'
                ) THEN
                    ALTER TABLE sales_order
                    ADD CONSTRAINT sales_order_code_unique UNIQUE (code);
                END IF;
            EXCEPTION
                WHEN duplicate_object THEN NULL;
            END $$;
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name="salesorder",
                    name="code",
                    field=models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=100,
                        null=True,
                        unique=True,
                    ),
                ),
            ],
            database_operations=[],
        ),
    ]
