# Generated by Django 5.2.12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sales", "0002_code_counter_and_sales_order_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="salesorder",
            name="state",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("confirmed", "Confirmed"),
                    ("paid", "Paid"),
                    ("void", "Void"),
                ],
                db_index=True,
                default="draft",
                max_length=20,
            ),
        ),
    ]
