# Generated by Django 5.2.12 on 2026-03-25 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0008_partner_normalized_unique"),
    ]

    operations = [
        # Column `sales_order.order_type` already exists (legacy).
        # Register it in Django's migration state without altering the DB.
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AddField(
                    model_name="salesorder",
                    name="order_type",
                    field=models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        max_length=20,
                    ),
                ),
            ],
        ),
    ]

