# Generated by Django 5.2.12 on 2026-03-27 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0013_partner_legal_entity_type_state_only'),
        ('sales', '0013_sales_order_project_nullable'),
    ]

    operations = [
    ]
