# Generated by Django 5.2.12 on 2026-03-28 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0010_table_number_unique_name_global'),
        ('sales', '0016_partner_unique_name_corporate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='is_customer',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterConstraint(
            model_name='partner',
            name='unique_name_corporate',
            constraint=models.UniqueConstraint(fields=('name', 'is_corporate'), name='unique_name_corporate', violation_error_message='That name’s already taken for this partner type (corporate vs non-corporate) — try another one.'),
        ),
    ]
