# Generated by Django 5.2.12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("master", "0002_align_integer_pks"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PurchaseOrder",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("code", models.CharField(blank=True, db_index=True, max_length=100, null=True, unique=True)),
                ("vendor_name", models.CharField(blank=True, default="", max_length=100)),
                ("vendor_phone", models.CharField(blank=True, default="", max_length=50)),
                ("time_transaction", models.DateTimeField()),
                ("is_active", models.BooleanField(default=True)),
                ("state", models.CharField(choices=[("draft", "Draft"), ("confirmed", "Confirmed"), ("void", "Void")], db_index=True, default="draft", max_length=20)),
                ("update_at", models.DateTimeField(auto_now=True)),
                ("created_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="purchase_orders", to=settings.AUTH_USER_MODEL)),
            ],
            options={"db_table": "purchase_order", "ordering": ["-time_transaction", "-id"]},
        ),
        migrations.CreateModel(
            name="PurchaseOrderLine",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("quantity", models.DecimalField(decimal_places=2, max_digits=20)),
                ("unit_price", models.DecimalField(decimal_places=2, max_digits=20)),
                ("is_active", models.BooleanField(default=True)),
                ("update_at", models.DateTimeField(auto_now=True)),
                ("product", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="purchase_order_lines", to="master.product")),
                ("purchase_order", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="lines", to="purchase.purchaseorder")),
            ],
            options={"db_table": "purchase_order_line"},
        ),
        migrations.CreateModel(
            name="PurchaseOrderLineTax",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("update_at", models.DateTimeField(auto_now=True)),
                ("purchase_order_line", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="line_taxes", to="purchase.purchaseorderline")),
                ("tax", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="purchase_order_line_taxes", to="master.tax")),
            ],
            options={"db_table": "purchase_order_line_tax"},
        ),
        migrations.AddIndex(model_name="purchaseorder", index=models.Index(fields=["-update_at"], name="idx_po_update_at")),
        migrations.AddIndex(model_name="purchaseorder", index=models.Index(fields=["state", "-update_at"], name="idx_po_state_update_at")),
        migrations.AddIndex(model_name="purchaseorder", index=models.Index(fields=["created_by"], name="idx_po_created_by")),
        migrations.AddIndex(model_name="purchaseorderline", index=models.Index(fields=["purchase_order", "id"], name="idx_pol_order_id")),
        migrations.AddConstraint(
            model_name="purchaseorderlinetax",
            constraint=models.UniqueConstraint(fields=("purchase_order_line", "tax"), name="purchase_order_line_tax_purchase_order_line_id_tax_id_key"),
        ),
    ]
