# Generated by Django 5.2.12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("tx_type", models.CharField(choices=[("i", "Incoming"), ("o", "Outgoing")], db_index=True, max_length=1)),
                ("source_table", models.CharField(db_index=True, max_length=64)),
                ("source_pk", models.BigIntegerField(db_index=True)),
                ("reference_code", models.CharField(blank=True, default="", max_length=100)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=20)),
                ("currency_code", models.CharField(default="IDR", max_length=3)),
                ("transaction_at", models.DateTimeField()),
                ("note", models.TextField(blank=True, default="")),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="payments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"db_table": "payment"},
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(fields=["tx_type", "source_table", "source_pk"], name="idx_pay_source"),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(fields=["-transaction_at"], name="idx_pay_tx_at"),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(fields=["created_by"], name="idx_pay_created_by"),
        ),
    ]
