# Generated by Django 5.2.12 on 2026-03-22 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CodeCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('counter_family', models.CharField(db_index=True, max_length=20)),
                ('year', models.PositiveSmallIntegerField()),
                ('last_value', models.PositiveIntegerField(default=0)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'code_counter',
                'constraints': [models.UniqueConstraint(fields=('counter_family', 'year'), name='code_counter_family_year_uniq')],
            },
        ),
    ]
