# Generated by Django 5.2.12 on 2026-03-25 13:15

from django.db import migrations


DROP_SQL = """
-- Drop payment artifacts (user requested reset).
-- CASCADE removes dependent views/constraints/indexes that reference payment.
DROP VIEW IF EXISTS payment_with_source CASCADE;
DROP TABLE IF EXISTS payment CASCADE;
""".strip()


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_code_counter_and_sales_order_code"),
    ]

    operations = [
        migrations.RunSQL(
            sql=DROP_SQL,
            reverse_sql=migrations.RunSQL.noop,
        )
    ]

